Solve undefined reference to `memcpy'
Seems to be due to the compiler replacing memcpy with inline code. Patch
from:
http://www.cubieforums.com/index.php/topic,838.msg5065.html#msg5065